const envVars = {
  API_URL: String(process.env.NEXT_PUBLIC_APIURL),
  NEXT_PUBLIC_CONTRACT_ADDRESS: String(process.env.NEXT_PUBLIC_CONTRACT_ADDRESS),
  NEXT_PUBLIC_ALCHEMY_ID: String(process.env.NEXT_PUBLIC_ALCHEMY_ID),
  NEXT_PUBLIC_INFURA_ID: String(process.env.NEXT_PUBLIC_INFURA_ID),
  NEXT_PUBLIC_ETHERSCAN_API_KEY: String(process.env.ETHERSCAN_API_KEY),
  IPFS_GATEWAY: String(process.env.IPFS_GATEWAY),
  NEXT_PUBLIC_GATEWAY_OPTIMISM_RPC: String(process.env.NEXT_PUBLIC_GATEWAY_OPTIMISM_RPC),
  NEXT_PUBLIC_GATEWAY_POLYGON_RPC: String(process.env.NEXT_PUBLIC_GATEWAY_POLYGON_RPC),
  NEXT_PUBLIC_GNOSIS_RPC_URL: String(process.env.NEXT_PUBLIC_GNOSIS_RPC_URL),
}

export default envVars
